# Generated by Django 3.1 on 2020-08-10 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculate_stream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculations',
            name='id',
        ),
        migrations.AlterField(
            model_name='calculations',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
