# Generated by Django 3.1 on 2020-08-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate_stream', '0002_auto_20200810_0156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculations',
            new_name='Calculation',
        ),
    ]
