# Generated by Django 3.1 on 2020-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate_stream', '0003_auto_20200810_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
